# Generated by Django 4.1.13 on 2024-07-27 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountsApp', '0002_remove_users_confirm_password_alter_users_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='confirm_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
